version: '3'
services:
  sync:
    image: wazopbx/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  auth:
    image: "wazopbx/wazo-auth-mock"
    ports:
      - "9497"

  provd:
    image: wazo-provd-tests
    volumes:
      - "../..:/usr/src/wazo-provd/"
      - "./etc/wazo-provd/config.yml:/etc/wazo-provd/config.yml"
      - "./keys/wazo-provd-key.yml:/var/lib/wazo-auth-keys/wazo-provd-key.yml"
      - "./provd/configs/base:/var/lib/wazo-provd/jsondb/configs/base"
      - "./provd/configs/default:/var/lib/wazo-provd/jsondb/configs/default"
      - "./provd/configs/defaultconfigdevice:/var/lib/wazo-provd/jsondb/configs/defaultconfigdevice"
      - "./provd/configs/autoprov:/var/lib/wazo-provd/jsondb/configs/autoprov"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/usr/local/lib/python2.7/site-packages/xivo"
    ports:
      - "8666"
      - "8667"
      - "69/udp"

  pluginserver:
    image: trinitronx/python-simplehttpserver
    volumes:
      - "./provd/plugins/pkgs:/var/www"
    ports:
      - "8080"
