version: '3'
services:
  sync:
    image: wazoplatform/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  auth:
    image: wazoplatform/wazo-auth-mock
    ports:
      - "9497"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
    volumes:
      - type: tmpfs
        target: /var/lib/rabbitmq

  provd:
    image: wazo-provd-tests
    volumes:
      - "../..:/usr/src/wazo-provd/"
      - "./etc/wazo-provd/config.yml:/etc/wazo-provd/config.yml"
      - "./keys/wazo-provd-key.yml:/var/lib/wazo-auth-keys/wazo-provd-key.yml"
      - "./provd/configs/base:/var/lib/wazo-provd/jsondb/configs/base"
      - "./provd/configs/default:/var/lib/wazo-provd/jsondb/configs/default"
      - "./provd/configs/defaultconfigdevice:/var/lib/wazo-provd/jsondb/configs/defaultconfigdevice"
      - "./provd/configs/autoprov:/var/lib/wazo-provd/jsondb/configs/autoprov"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/opt/venv/lib/python3.9/site-packages/xivo"
    ports:
      - "8666"
      - "8667"
      - "69/udp"

  pluginserver:
    image: trinitronx/python-simplehttpserver
    volumes:
      - "./provd/plugins/pkgs:/var/www"
    ports:
      - "8080"

  postgres:
    image: wazoplatform/wazo-provd-db
    ports:
      - "5432"
